version: "3.9"
services:
  backend:
    image: tuannm74/hello:1.1 
    container_name: backend 
    build: ./
    ports:
      - "5000:5000"
  networks:                                                                                                                                                                                                                                      
	- tuannm74 
  frontend:
    build: ./ 
    depends_on:
     - backend
  networks:                                                                                                                                                                                                                                      
     - tuannm74  
  ports:
     - "80:80"
     - "443:443" 
  command: certbot --nginx -d api.suusuu.site -m minhtuanvb96@gmail.com  --agree-tos  
networks:
 tuannm74:
  driver: bridge 