apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx-deployment
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest 
        ports:
        - name: mqtt
          containerPort: 1883
        - name: dashboard
          containerPort: 18083
        environment:       
        - EMQX_AUTH__USER__PASSWORD_HASH=plain      
        - EMQX_AUTH__USER__1__USERNAME=tuan   
        - EMQX_AUTH__USER__1__PASSWORD=Tuan@2019
        - EMQX_LOADED_PLUGINS=emqx_prometheus
        - EMQX_PROMETHEUS__PUSH__GATEWAY__SERVER=:9091
        - EMQX_PROMETHEUS__INTERVAL=15000
        volumes:
          - ./emqx_statsd.conf:/etc/emqx_statsd.conf