apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsapp
  labels:
    app: rsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsapp
  template:
    metadata:
      labels:
        app: rsapp
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest 
        ports:
        - name: mqtt
          containerPort: 1883
        - name: dashboard
          containerPort: 18083
        environment:       
        - EMQX_AUTH__USER__PASSWORD_HASH=plain      
        - EMQX_AUTH__USER__1__USERNAME=tuan   
        - EMQX_AUTH__USER__1__PASSWORD=Tuan@2019
        - EMQX_LOADED_PLUGINS=emqx_prometheus
        - EMQX_PROMETHEUS__PUSH__GATEWAY__SERVER=pushgateway:9091
        - EMQX_PROMETHEUS__INTERVAL=15000
        depends_on:
          - pushgateway        
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - name: rabitmq
          containerPort: 5672
        - name: dashboard
          containerPort: 15672
        - name: grafana
          containerPort: 15692          
      - name: prometheus
        image: prom/prometheus:latest
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: dashboard
          containerPort: 9090  
      - name: pushgateway
        image: prom/pushgateway
        ports:
        - name: dashboard
          containerPort: 9091  
        depends_on:
          - prometheus
          
