# -*- mode: ruby -*-
# vi: set ft=ruby :
# Tạo máy ảo từ box ubuntu, gán địa chỉ IP, đặt hostname, gán 2GB bộ nhớ, 1 cpus  
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.network "private_network", ip: "192.168.10.101"
  config.vm.hostname = "worker2"
  config.vm.provider "virtualbox" do |vb|
      vb.name = "worker2"
      vb.cpus = 1
      vb.memory = "1048"
  end
  # Chạy file install-docker-kube.sh sau khi nạp Box
  config.vm.provision "shell", path: "./../install-docker-kube.sh"
  # Chạy các lệnh shell
  config.vm.provision "shell", inline: <<-SHELL
      # enable ssh
      sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
      sudo systemctl reload sshd
      # Đặt pass 123 có tài khoản root và cho phép SSH
      echo -e "123\n123" | passwd root >/dev/null 2>&1
      echo "export TERM=xterm" >> /etc/bash.bashrc
      echo "Update /etc/hosts file"
      sudo cat >>/etc/hosts<<EOF
          192.168.10.100   master
          192.168.10.101   worker1
          192.168.10.102   worker2
      EOF
  SHELL
end
