apiVersion: v1
kind: Service
metadata:
  name: rambit
spec:
  selector:
     app: rambit
  type: NodePort
  ports:
    - name: dashboard
      port: 15672
      targetPort: 15672
      nodePort: 32672
    - name: http
      port: 5672
      targetPort: 5672
      nodePort: 31672
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rambit-deployment
  labels:
    app: rambit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rambit
  template:
    metadata:
      labels:
        app: rambit
    spec:
      containers:
      - name: rambit
        image: rabbitmq:3-management-alpine
        ports:
        - name: http
          containerPort: 5672
        - name: dashboard
          containerPort: 15672
        - name: grafana
          containerPort: 15692
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rambitmqsecret
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rambitmqsecret
              key: RABBITMQ_PASSWORD
        #envFrom:
        #- secretRef:
            #name: rambitmqsecret
